[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  targetPort = 3000

# Enable Netlify Identity for Decap CMS
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Content API endpoint
[[redirects]]
  from = "/api/content/*"
  to = "/.netlify/functions/scanContent"
  status = 200

# Cache control for dynamic content
[[headers]]
  for = "/.netlify/functions/scanContent"
  [headers.values]
    Cache-Control = "public, max-age=60, s-maxage=300"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Cache control for content files
[[headers]]
  for = "/content/**/*.md"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=600"

# Build hooks for automatic content regeneration
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Context-specific settings
[context.production]
  command = "npm run build:prod"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

# Build event hooks
[[plugins]]
  package = "@netlify/plugin-sitemap"

# Enable file-based routing for content
[[edge_functions]]
  function = "content-refresh"
  path = "/refresh-content"