[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  targetPort = 3000

# Enable Netlify Identity for Decap CMS
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Handle media files for CMS
[[redirects]]
  from = "/assets/uploads/*"
  to = "/assets/uploads/:splat"
  status = 200

# ===== PERFORMANCE OPTIMIZATIONS =====

# Cache static assets with immutable content hash for 1 year
[[headers]]
  for = "/assets/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Cache images for 1 year (they have content hashes)
[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Cache fonts for 1 year
[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Cache uploaded media for 1 year but allow revalidation
[[headers]]
  for = "/assets/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"
    X-Content-Type-Options = "nosniff"

# HTML files - short cache with revalidation
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

# Root HTML
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

# Service Worker (if added in future)
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Content files (markdown, etc.)
[[headers]]
  for = "/content/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    X-Content-Type-Options = "nosniff"